### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by strycore** [andreas-jonsson/openwar#4]
I'm trying to build the project on Ubuntu 16.04. Having little knowledge in Go, I'm relying on the Travis.ci file to build the project.

So far I have:
```

export GOPATH=$(pwd)
go get
```

which results in:
```

go install: no install location for directory /home/strider/Projects/buildbot/games/openwar/openwar-src outside GOPATH
	For more details see: go help gopath
```

Some brief instructions on how to get the project to build in the README would be greatly appreciated :D 

Update: I managed to build and run the project but that doesn't change the core of the issue ;)

**Comment by andreas-jonsson** [comment]
Hi!

Sorry about that...
I'm in the process finalizing the automated builds and build-scripts.

I'm not on Ubuntu at the moment but I think the steps are like this if you want to test it:

1.) Download/apt-get **go1.6, gtk2-dev, sdl2-dev, sdl2_mixer-dev** from your distro. (mixer needs to be built with timidity support... usualy the default.)

2.) **mkdir $HOME/Go**
    Create a workspace for Go

3.) **export GOPATH=$HOME/Go**
    or set it up in **.bashrc** for future use

4.) **go get github.com/andreas-jonsson/openwar**

5.) **cd $GOPATH/src/github.com/andreas-jonsson/openwar**

6.) **go get**
   Not sure you need this step... but do it just in case something is missing. :)

7.) **go run openwar.go**
   or just, _go run openwar.go_

I hope that will get you going. :)

**Comment by andreas-jonsson** [comment]
Readme is updated.
